server:
  port: 8094
spring:
  application:
    name: loan-approval-service
  datasource:
    url: jdbc:mysql://localhost:3306/loan_db?createDatabaseIfNotExist=true
#    host: 127.0.0.1
    username: root
    password:
#    password: examly
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          validation:
            mode=none:
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5Dialect


